title: "Professional Engineering Blog"
description: "Sharing knowledge & experience in engineering management, EMS, product design, and IT."
url: "https://kpanuwat.github.io"
theme: jekyll-theme-cayman
#theme: minima # หรือเลือกธีมอื่น เช่น jekyll-theme-cayman, jekyll-theme-modernist
